
targets:

  - name: laf
    out: liblaf.so
    cflags: [ -fPIC, -g ]
    ldflags: [ -shared ]
    ldlibs: [ -llua ]
    subdirs:
      - core
      - evl
    sources:
      - core/util
      - core/class
      - evl/evloop

  - name: laugh_test
    depend: [ laf ]
    cflags: [ -g ]
    ldlibs: [ -llua ]
    sources:
      - main
      - foo
